# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ffda1824396fa09cc3a0ec6b0ba12652689b465cf281c9d96f08375d611bfcb8419578aa4ddecbe179acfff5d4154a4e476555aa8cf1f05b98dfc9e19505ce9

test:
  secret_key_base: 2151bdea138d731e3b5d0087298d18540f0d964583bf4c39bf5799cc3f94aef07cedd791302003d344ae0f221ecd1cd4785b8e317f883c20f6629cdd41a67db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
